services:
  postgres:
    image: postgres:18.1
    container_name: sanaap-db
    ports:
      - 5432:5432
    volumes:
      - ./.cache/postgres_data:/var/lib/postgresql
    env_file:
      - .env

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: sanaap-s3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./.cache/minio_data:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"

  redis:
    image: redis:8.4.0
    container_name: sanaap-cache
    ports:
      - "6379:6379"
    volumes:
      - ./.cache/redis_data:/data
